# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Eric Nord
tagline:             'A Full Stack Web Developer'
description:         'The personal site of Eric Nord'
url:                 'http://thateric.github.io/'
github:             'https://github.com/ThatEric/thateric.github.io'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Eric Nord
  email:             enord6@gmail.com

# Custom vars
version:             1.0.0
